### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by mcmenaminadrian** [ConorMcPersonal/Toaster#2]
Guess we need to set some - you seem to like snake_case - we going with that? Real programmers use camelCase in their C, but I'll live :-)

**Comment by ConorMcPersonal** [comment]
It's a great frustration to everyone I ever code with that having been
through so many languages and coding styles over the years, I don't care
anymore. I intermingle them willy-nilly all the time.

Sorry.

You pick a style you like and I'll try to stick with it!
