### ISSUE TITLE
Manager's face?

### ISSUE THREAD

**Issue by mcmenaminadrian** [ConorMcPersonal/Toaster#27]
I have the score 'numbers' printing flushed right (code to follow shortly). How about having a managers face flushed left on the same line? Depending on how things are going could be happy, neutral, sad etc. Just need to do the 16x16 grid ('graphic design is my passion') for them and code them up.
Any other things we could put on the top line in the same way?

**Comment by ConorMcPersonal** [comment]
Yes we could drive that based on the reputation - 1000 is neutral, 1500+ is happy, 500- is unhappy, 200- is angry

**Comment by mcmenaminadrian** [comment]
In PR
