### ISSUE TITLE
Now possible to overflow on score

### ISSUE THREAD

**Issue by mcmenaminadrian** [ConorMcPersonal/Toaster#31]
ie score more than 0x7FFF and get a negative score that way

**Comment by ConorMcPersonal** [comment]
That was always theoretically possible, just way too hard to achieve in
reverse Polish.

Could make It a long, but that would need more real estate.

Make it a long but display it divided by 10? Or divided by 8 to allow the
operation to be done via bit-shifting?

**Comment by mcmenaminadrian** [comment]
Long >> 3 sounds like a good idea
