### ISSUE TITLE
Bit slow now

### ISSUE THREAD

**Issue by mcmenaminadrian** [ConorMcPersonal/Toaster#35]
And too easy?

**Comment by ConorMcPersonal** [comment]
The music does slow it down, let me see if I can tweak the note settings to
improve it. We could also increase new customer probability to ramp it up
again, so it is tunable in different ways at least.

**Comment by mcmenaminadrian** [comment]
We can also dispense with the commands heading so we can start to have longer order lists

**Comment by ConorMcPersonal** [comment]
How about if the maximum length of order list increases each day - could do
the same with customer frequency?
