### ISSUE TITLE
Time shows from start of game even after restart

### ISSUE THREAD

**Issue by ConorMcPersonal** [ConorMcPersonal/Toaster#44]
Time should show and start immediately at start of game, without customers or toast

**Comment by ConorMcPersonal** [comment]
Think this might be resolved now?

**Comment by mcmenaminadrian** [comment]
It has become satisfyingly very difficult to play now but as a result I cannot get to day 2 to verify what is going on!

**Comment by mcmenaminadrian** [comment]
No longer an issue
