### ISSUE TITLE
Reputation face disappears

### ISSUE THREAD

**Issue by ConorMcPersonal** [ConorMcPersonal/Toaster#49]
On Day 2?  Not sure exactly...

**Comment by mcmenaminadrian** [comment]
Reputation drawing code never seems to be called on day 2. Not sure why

**Comment by mcmenaminadrian** [comment]
Have a look in https://github.com/ConorMcPersonal/Toaster/tree/update_screen_furniture @ConorMcPersonal - if you see in customer.c (line 160) there is a method to ensure the reputation face gets redrawn if execution ever gets this far on day 2 - but plainly it never does. Can you see what is wrong here??

**Comment by mcmenaminadrian** [comment]
cracked it

**Comment by mcmenaminadrian** [comment]
Fixed
