### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by ConorMcPersonal** [ConorMcPersonal/Toaster#5]
Better indications on slot monitor (slot number, icons for each bar?)
Multiple slots (should be easy to implement now)
Stream of orders to be filled - maybe level complete after a certain order count?
Indication of successful command and unsuccessful command (beep tones?  Colour?)
More variability in toasting/bread types

**Comment by mcmenaminadrian** [comment]
I'm working on a stack displayed down the screen. Guess we need to sort priorities here so we actually make proper progress and not just (me in particular) do what we feel like :-)
We can set up a kanban board on this thing I believe

**Comment by ConorMcPersonal** [comment]
Have merged the PR, bit confused about what is going on with the control buffer indices though!?

Think we need to agree on main screen layout - I had in mind to have additional slots horizontally.   The abstract command list (1PW1T etc at bottom of screen) was an attempt to preserve screen real estate - plus it made the game more crap and therefore on brief!

I also had in mind an 'orders' list (can't just be banging out white toast for the sake of it) much like you have created here for the stack.

More generally I still see us as trying stuff out here for now but don't want it to be a frustrating 'step on each others toes' experience!

**Comment by mcmenaminadrian** [comment]
I think the "crapness" is meant to be the mundanity of the concept and the
sheer tedium of playing but also that - to do well - you need some high
production values. lol

**Comment by ConorMcPersonal** [comment]
Sorry updated my comment above - didn't think you'd be online.  I have a 4.30 start tomorrow though so signing off!
