### ISSUE TITLE
Snap firing after Day 1

### ISSUE THREAD

**Issue by ConorMcPersonal** [ConorMcPersonal/Toaster#54]
It's now possible to do well on Day 1, then get fired almost immediately on Day 2.  Probably related to tighter customer timing, driven by the introduction of toast_ticks.  Needs looking at.

To help with testing we probably need some code to help us deliver perfect toast every time with zero user input!

**Comment by ConorMcPersonal** [comment]
Pretty sure this is driven by min reputation - snap firing happens if/when a customer gets angry

**Comment by mcmenaminadrian** [comment]
There is something fundamentally broken about reputation handling on day 2 but not yet got to the bottom of it.

**Comment by ConorMcPersonal** [comment]
Am giving a minimum of 100 rep leeway at start of day 2 (provided you're not fired)
