### ISSUE TITLE
Day number does not reset.  Ever?

### ISSUE THREAD

**Issue by ConorMcPersonal** [ConorMcPersonal/Toaster#59]
Grrrr static variables suck

**Comment by ConorMcPersonal** [comment]
We had a static variable called game_day and a local variable for the game named gameDay, doing basically the same job.  I will boil down to game_day but static variables seem to be a source of "no-reset" bugs.

**Comment by mcmenaminadrian** [comment]
Ah, I removed one set of updates for the statics because they seemed to be redundant - perhaps the second ones I was looking at weren't for statics at all.
