### ISSUE TITLE
Reputation is all a bit odd now

### ISSUE THREAD

**Issue by mcmenaminadrian** [ConorMcPersonal/Toaster#63]
I made a bit of a booboo with the screen furniture PR but I've fixed that and it still seems to be the case that we cannot be sad anymore - we go straight from neutral to getting fired

**Comment by ConorMcPersonal** [comment]
I know where this comes from - min allowed reputation goes up day by day.  I can fix (I think)

**Comment by ConorMcPersonal** [comment]
I have a fix in a local branch - one liner
